### PR TITLE
Reorganizing the ProjectState possible values and their usage in RepairNator (issue #91)

### PR DESCRIPTION
**Pull request by fermadeiral**

### CODE REVIEW

**Comment by fermadeiral** [comment]
I also
- put the `CheckoutRepository` and `CheckoutType` in a new package (`fr.inria.spirals.repairnator.process.step.checkoutrepository`);
- added the "real state" in the Bears spreadsheet;
- changed some messages of the logger;
- and did other minor changes.

**Comment by fermadeiral** [comment]
Some tests fail because of the reorganization of the ProjectState possible values:

```
Failed tests: 
  TestComputeSourceDir.testComputeSourceDir:62 
Expected: is <SOURCEDIRCOMPUTED>
     but: was <NOTTESTABLE>
  TestNopolRepair.testNopolRepair:82 
Expected: is <PATCHED>
     but: was <CLASSPATHNOTCOMPUTED>
  TestTestProject.testTestProjectWhenFailing:57 
Expected: is <false>
     but: was <true>

Tests run: 23, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by surli** [comment]
> Some tests fail because of the reorganization of the ProjectState possible values

Update the tests then.

**Comment by fermadeiral** [comment]
> Update the tests then.

But did you review and agree with the new organization? I won't change the tests before that. By the way, I was thinking about it and I think that the problem may be not because of the reorganization. It doesn't make sense if it was.

**Pull request merged**
